### ISSUE TITLE
无法控制播放进度，时间显示 NaN:NaN:NaN

### ISSUE THREAD

**Issue by icandura** [grzhan/hexo-tag-aplayer#12]
我开启了hexo里面的 post_asset_folder 选项
新建了一篇post文件是 test.md
同时在 test 文件夹下放了文件 01.mp3
通过这样的方式插入播放
`{% aplayer "01" "Authur" "01.mp3" %}`
能够正常播放，但是就是无法控制进度，
进度条不走动，正常播放时时间显示：
` -00:31(播放时间) / NaN:NaN:NaN`
拖动进度条后时间显示变成：
` - NaN:NaN:NaN / NaN:NaN:NaN `

**Comment by grzhan** [comment]
请告知使用的aplayer版本（`npm list`）

**Comment by icandura** [comment]
-- hexo-tag-aplayer@2.0.1
  +-- aplayer@1.5.8

**Comment by grzhan** [comment]
@icandura 排查了下可能是上游 aplayer 的问题，可能需要去咨询下 aplayer 那边

**Comment by icandura** [comment]
恩，不知怎么的今天再看的时候突然又正常了。。。
