### ISSUE TITLE
[Request] Lyrics: "回访 顺带问问歌词的坑（"

### ISSUE THREAD

**Issue by Myer921** [grzhan/hexo-tag-aplayer#4]
不知道作者大大你何时能把歌词的坑填好（

**Comment by grzhan** [comment]
之前迟迟不支持歌词的原因是，若要支持歌词， Tag 的形式必须变成拥有闭合标签的形式（形如 `<aplayer></aplayer>`），这样的话若不使用歌词的时候使用体验似乎不是很好。

不过刚才想了下，可能歌词和插件的标签可以分开做，所以应该很快就能支持歌词。

**Comment by Myer921** [comment]
好 我那等着～

**Comment by Myer921** [comment]
好像我这边有人把坑填了 然后我不能在fork这个项目了
我想提交一个来的= =

**Comment by grzhan** [comment]
@Myer921 如果是写dplayer的话其实把代码拿过去然后自己建个独立的项目就好（在Readme通过inspired等说法进行说明）。

如果有dalao已经写好歌词的feature的话可以从这个项目fork出来，然后提交pr，我会merge进去。

这是比较常规也是比较礼貌的做法。

**Comment by Myer921** [comment]
已经提交
