### ISSUE TITLE
Error Error ENONET: no such file or directory. scandir '...\font'

### ISSUE THREAD

**Issue by grzhan** [grzhan/hexo-tag-aplayer#7]
> ERROR Plugin load failed:
> Error ENONET: no such file or directory. scandir 'C:\Hexo\node_modules\aplayer\dist\font'

Solution:

http://login926.github.io/2016/07/20/HexoMedia/

**Comment by DIYgod** [comment]
新版 APlayer 使用 inline svg 代替 web font，已经不需要 font 文件夹了

另外新版的 css 通过 js 自动引用，不需要手动加载了

即：只需要一个 APlayer.min.js 即可

请更新插件🌚~~

**Comment by grzhan** [comment]
@DIYgod 貌似是用了webpack？

OK，稍后更新

**Comment by DIYgod** [comment]
嗯，css和js打包到一起了嘻嘻

**Comment by grzhan** [comment]
@DIYgod 了解了，看来以后我也要关注下aplayer的大版本更新

**Comment by DIYgod** [comment]
点一下右上角的watch或者订阅[tags](https://github.com/DIYgod/APlayer/tags.atom)就行啦
