### ISSUE TITLE
请问有支持播放列表的考虑么？

### ISSUE THREAD

**Issue by yizhilee** [grzhan/hexo-tag-aplayer#8]

**Comment by grzhan** [comment]
看了下，应该不难实现，这周可以搞下。

预计是用形如`{% aplayerlist %} ... {% endaplayerlist %}` 这样的 tag 来做

**Comment by yizhilee** [comment]
嗯，感谢，最好能支持随机播放。

**Comment by grzhan** [comment]
`hexo-tag-aplayer@2.0.0-beta.0` 已支持播放列表。

文档已更新，请测试使用，如有问题请报告。

**Comment by yizhilee** [comment]
不好意思，需要自己编译吗？

**Comment by grzhan** [comment]
应该不需要

**Comment by grzhan** [comment]
@yizhilee 你好，请问新版本的播放列表是否可以正常使用？如果可以的话我就开始考虑发正式版本了。

**Comment by yizhilee** [comment]
@grzhan 我这里安装之后无法正常启动服务器，请问是直接 git clone 到本地吗？

**Comment by grzhan** [comment]
@yizhilee 在博客所在的文件夹安装 `npm install --save hexo-tag-aplayer@2.0.0-beta.0`

如果 hexo 生成博客失败（`hexo g`），请把错误信息发出来

**Comment by yizhilee** [comment]
@grzhan 成功安装之后单曲可以看到播放器，列表找不见。

**Comment by grzhan** [comment]
@yizhilee 请参照README中的`with playlist (new in 2.0)`来创建 `aplayer` 播放列表。

基本上就是`{%aplayerlist%} options with json format {%endaplayerlist%}` 这样的格式写法。

如果不生效，请打开浏览器的开发者工具，查看”控制台（console）“标签页下的错误信息并发给我。

**Comment by yizhilee** [comment]
@grzhan 就是按照 README 中的格式创建的，控制台也没有错误信息……

**Comment by grzhan** [comment]
@yizhilee 如果可以的话把博客部署到线上我看下？

**Comment by yizhilee** [comment]
@grzhan 找到原因了，REDEME 里面的 autoplay 没加双引号……

**Comment by grzhan** [comment]
@yizhilee 抱歉，现在可以正常播放了吗

**Comment by yizhilee** [comment]
@grzhan 可以了，歌词格式有什么要求吗，无法显示歌词。

**Comment by grzhan** [comment]
一般LRC格式应该就可以了（[http://blog.grr.moe/2015/12/04/CoCo/caffeine.txt](http://blog.grr.moe/2015/12/04/CoCo/caffeine.txt)）

如果没有显示的话看看是不是`showlrc`选项的问题，如果使用相对 URL 路径来载入歌词（同 README 的示例格式）那么`showlrc`需要设置为 3 。

详情可以参考 [http://aplayer.js.org/docs/#lrc-format](http://aplayer.js.org/docs/#lrc-format)

如果播放列表歌曲播放出现异常，请把”控制台（console）“标签页下的错误信息发给我（如果有），若没有，可能是 aplayer 的问题，我会排查并向 aplayer 的开发组核实。

**Comment by yizhilee** [comment]
@grzhan 歌词可以正常显示了；播放列表异常没有错误信息。

**Comment by grzhan** [comment]
@yizhilee 多谢，尝试解决这个问题（或者向上游发 issue）之后应该会发正式版本。

**Comment by yizhilee** [comment]
@grzhan 部署在服务器上一切正常：https://blog.yizhilee.com/post/my-favourite-songs/，看来只有在本地会出现这个问题；第一个播放器是 163music-APlayer-you-get，第二个是 hexo-tag-aplayer。

**Comment by grzhan** [comment]
@yizhilee 了解，再次感谢你的协助。
