### ISSUE TITLE
播放本地音乐需要完全加载才能播放

### ISSUE THREAD

**Issue by LdBeth** [grzhan/hexo-tag-aplayer#9]
不支持边加载边播放吗？

还是因为github的问题？

<https://ldbeth.github.io/about/>

**Comment by grzhan** [comment]
无法复现边加载边播放的问题，可能是对于问题的理解有出入？

![screenshot](https://i.v2ex.co/lp5Lddr3.png)

或者请告知使用的浏览器、插件以及 aplayer 版本

**Comment by LdBeth** [comment]
不知道为什么。现在并没有这个问题了。十分抱歉打扰您了。
